/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Dimension;
import java.awt.Graphics;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import models.CauHoiTracNghiem;
import models.CauHoiTuLuan;
import models.DeThi;
import models.MonHoc;

/**
 *
 * @author hungv
 */
public class DeThiMau extends javax.swing.JFrame {

    private DeThi deThiSelected=new DeThi();
    private ArrayList<DeThi>dsDe=new ArrayList<>();
    
    private MonHoc monHocSelected;
    private ArrayList<MonHoc> listMonHoc = new ArrayList<>();
    
    /**
     * Creates new form DeThiSan
     */
    public DeThiMau(MonHoc monHocSelected) {
        initComponents();
        this.setTitle("Đề thi mẫu");
        this.monHocSelected = monHocSelected;
        readDanhSachMonHoc();
        dsDe = monHocSelected.getDsDeThi();
        hienThiDeThi();
    }
    
     public DeThiMau() {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setTitle("Đề thi mẫu");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel() {
            ImageIcon icon = new ImageIcon("src\\anh\\dethimau.jpg");
            public void paintComponent(Graphics g){
                Dimension d = getSize();
                g.drawImage(icon.getImage(), 0, 0, d.width, d.height, null);
                setOpaque(false);
                super.paintComponent(g);
            }
        };
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnXuatRaFile = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listDeThiMau = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaNoiDungDe = new javax.swing.JTextArea();
        btnXoaDeThi = new javax.swing.JButton();
        btnSuaDeThi = new javax.swing.JButton();
        btnQuayLai = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("DANH SÁCH ĐỀ THI");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("NỘI DUNG ĐỀ THI");

        btnXuatRaFile.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnXuatRaFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anh/xuatfile.png"))); // NOI18N
        btnXuatRaFile.setText("Xuất ra file");
        btnXuatRaFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatRaFileActionPerformed(evt);
            }
        });

        listDeThiMau.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        listDeThiMau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listDeThiMauMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listDeThiMau);

        txaNoiDungDe.setColumns(20);
        txaNoiDungDe.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        txaNoiDungDe.setRows(5);
        jScrollPane2.setViewportView(txaNoiDungDe);

        btnXoaDeThi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnXoaDeThi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anh/delete.png"))); // NOI18N
        btnXoaDeThi.setText("XÓA ĐỀ THI");
        btnXoaDeThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaDeThiActionPerformed(evt);
            }
        });

        btnSuaDeThi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSuaDeThi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anh/update.png"))); // NOI18N
        btnSuaDeThi.setText("SỬA ĐỀ THI");
        btnSuaDeThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaDeThiActionPerformed(evt);
            }
        });

        btnQuayLai.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnQuayLai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anh/back.png"))); // NOI18N
        btnQuayLai.setText("QUAY LẠI");
        btnQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayLaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQuayLai))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnXuatRaFile))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnXoaDeThi)
                        .addGap(18, 18, 18)
                        .addComponent(btnSuaDeThi)))
                .addGap(39, 39, 39))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXuatRaFile)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXoaDeThi, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSuaDeThi, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQuayLai, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnSuaDeThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaDeThiActionPerformed
        // TODO add your handling code here:
        deThiSelected=listDeThiMau.getSelectedValue();
        if(deThiSelected==null) {
            JOptionPane.showMessageDialog(null, "CHỌN ĐỀ THI MUỐN SỬA");
        }
        else {
            TaoDeThiBangTay tdt = new TaoDeThiBangTay(monHocSelected,deThiSelected);
            tdt.setVisible(true);
            this.setVisible(false);
        }
        
    }//GEN-LAST:event_btnSuaDeThiActionPerformed

    private void listDeThiMauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listDeThiMauMouseClicked
        // TODO add your handling code here:
        DeThi deThiDuocChon=listDeThiMau.getSelectedValue();
        String tracNghiem="";
        String tuLuan="";
        String tieuDe="";
        int i=1;
        
        tieuDe+="Đề thi : "+deThiDuocChon.getTenDe()+"          "+"Mã học phần : "+monHocSelected.getMaHocPhan()+"\n"+"Năm học : "+
                deThiDuocChon.getNamHoc()+"          "+"Học kỳ : "+deThiDuocChon.getKyHoc()+"          "+"Thời gian : "+deThiDuocChon.getThoiGian()+" phút"+"\n";
        for(CauHoiTracNghiem ch:deThiDuocChon.getDsCauHoiTN()) {
            tracNghiem+="Câu "+i+" : "+ch.inCauHoi();
            i++;
        }
        for(CauHoiTuLuan ch:deThiDuocChon.getDsCauHoiTL()) {
            tuLuan+="Câu "+i+" : "+ch.inCauHoi();
            i++;
        }
        String deThi=tieuDe+tracNghiem+tuLuan;
        txaNoiDungDe.setText(deThi);
    }//GEN-LAST:event_listDeThiMauMouseClicked

    private void btnXoaDeThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaDeThiActionPerformed
        // TODO add your handling code here:
        DeThi selectDeThi=listDeThiMau.getSelectedValue();
        if(selectDeThi == null) {
            JOptionPane.showMessageDialog(null, "CHỌN ĐỀ THI MUỐN XÓA");
        }
        else {
            dsDe.remove(selectDeThi);
            for(MonHoc monHoc : listMonHoc) {
                if(monHoc.getTenMonHoc().equals(monHocSelected.getTenMonHoc())) {
                    monHoc.setDsDeThi(dsDe);
                }
            }
            writeDanhSachMonHoc();
            hienThiDeThi();
            JOptionPane.showMessageDialog(null, "XÓA THÀNH CÔNG");
        }
    }//GEN-LAST:event_btnXoaDeThiActionPerformed

    private void btnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayLaiActionPerformed
        // TODO add your handling code here:
        XayDungDeThi xddt=new XayDungDeThi(monHocSelected);
        xddt.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnQuayLaiActionPerformed

    private void btnXuatRaFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatRaFileActionPerformed
        // TODO add your handling code here:
        deThiSelected=listDeThiMau.getSelectedValue();
        if(deThiSelected==null) {
            JOptionPane.showMessageDialog(null, "CHƯA CHỌN ĐỀ THI");
        }
        else {
            JFileChooser chooser=new JFileChooser();
            // hiển thị 1 hộp thoại để lưu file
            if(chooser.showSaveDialog(null)==JFileChooser.APPROVE_OPTION) {
                File file=chooser.getSelectedFile(); // 
                try {
                    FileWriter fw=new FileWriter(file+".doc");
                    fw.write(txaNoiDungDe.getText());
                    fw.close();
                    JOptionPane.showMessageDialog(null, "THÀNH CÔNG");
                } catch (Exception ex) {

                }
            }
        }
        
    }//GEN-LAST:event_btnXuatRaFileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeThiMau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeThiMau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeThiMau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeThiMau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeThiMau().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQuayLai;
    private javax.swing.JButton btnSuaDeThi;
    private javax.swing.JButton btnXoaDeThi;
    private javax.swing.JButton btnXuatRaFile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<DeThi> listDeThiMau;
    private javax.swing.JTextArea txaNoiDungDe;
    // End of variables declaration//GEN-END:variables

    private void hienThiDeThi() {
        DefaultListModel modelList=new DefaultListModel();
        for(DeThi deThi:dsDe) {
            modelList.addElement(deThi);
        }
        listDeThiMau.setModel(modelList);
    }

    private void writeDanhSachMonHoc() {
         try {
            FileOutputStream fileOutputStream = new FileOutputStream("DanhSachMonHoc.dat",false);
            ObjectOutputStream outputStream = new ObjectOutputStream(fileOutputStream);
            outputStream.writeObject(listMonHoc);
            outputStream.close();
            fileOutputStream.close();
        } catch (IOException e) {
            System.out.println(e.toString());
        }
    }

    private void readDanhSachMonHoc() {
        try {
            FileInputStream fileReader = new FileInputStream("DanhSachMonHoc.dat");
            ObjectInputStream inputStream = new ObjectInputStream(fileReader);
            listMonHoc = (ArrayList<MonHoc>) inputStream.readObject();
            inputStream.close();
            fileReader.close();

        } catch (FileNotFoundException ex) {
            Logger.getLogger(QuanLyMonHoc.class
                    .getName()).log(Level.SEVERE, null, ex);

        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(QuanLyMonHoc.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }
    
}
