/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import models.MonHoc;
import java.awt.Dimension;
import java.awt.Graphics;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author HuyLV
 */
public class QuanLyMonHoc extends javax.swing.JFrame {

    private ArrayList<MonHoc> listMonHoc = new ArrayList<>();
    private DefaultListModel modelListMonHoc = new DefaultListModel();
    private MonHoc selectedMonHoc;

    /**
     * Creates new form QuanLyMonHoc
     */
    public QuanLyMonHoc() {
        initComponents();
        this.setTitle("Quản lý môn học");
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        readListMonHoc();
        for (MonHoc mH : listMonHoc) {
            modelListMonHoc.addElement(mH);
        }
        jListDanhSachMonHoc.setModel(modelListMonHoc);
        txtTenMonHoc.setEnabled(false);
        txtMaHocPhan.setEnabled(false);
        txtGioiThieu.setEnabled(false);
        spSoChuong.setEnabled(false);
        btnLuu.setEnabled(false);
        btnCapNhat.setEnabled(false);
        btnXoa.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel(){
            ImageIcon icon = new ImageIcon("src\\anh\\quanlymonhoc.jpg");
            public void paintComponent(Graphics g){
                Dimension d = getSize();
                g.drawImage(icon.getImage(), 0, 0, d.width, d.height, null);
                setOpaque(false);
                super.paintComponent(g);
            }
        };
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListDanhSachMonHoc = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnTroVe = new javax.swing.JButton();
        txtTenMonHoc = new javax.swing.JTextField();
        txtMaHocPhan = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        spSoChuong = new javax.swing.JSpinner();
        btnLuu = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnThemMonHocMoi = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtGioiThieu = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Quản Lý Danh Sách Môn Học");

        jListDanhSachMonHoc.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jListDanhSachMonHoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListDanhSachMonHocMouseClicked(evt);
            }
        });
        jListDanhSachMonHoc.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListDanhSachMonHocValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jListDanhSachMonHoc);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Tên môn học ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Mã học phần ");

        btnTroVe.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnTroVe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anh/back.png"))); // NOI18N
        btnTroVe.setText("Trở về");
        btnTroVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTroVeActionPerformed(evt);
            }
        });

        txtTenMonHoc.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txtMaHocPhan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Số chương ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Giới thiệu ");

        spSoChuong.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        btnLuu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anh/luu.png"))); // NOI18N
        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anh/delete.png"))); // NOI18N
        btnXoa.setText("Xóa môn học");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnThemMonHocMoi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnThemMonHocMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anh/them.png"))); // NOI18N
        btnThemMonHocMoi.setText("Thêm môn học mới");
        btnThemMonHocMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemMonHocMoiActionPerformed(evt);
            }
        });

        btnCapNhat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anh/update.png"))); // NOI18N
        btnCapNhat.setText("Cập Nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        txtGioiThieu.setColumns(20);
        txtGioiThieu.setRows(5);
        jScrollPane2.setViewportView(txtGioiThieu);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnTroVe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnThemMonHocMoi))
                    .addComponent(jScrollPane1))
                .addGap(58, 58, 58)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTenMonHoc, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                            .addComponent(txtMaHocPhan, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                            .addComponent(spSoChuong, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCapNhat, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnXoa)))
                .addGap(72, 72, 72))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(177, 177, 177))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addGap(68, 68, 68)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTenMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMaHocPhan, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spSoChuong, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(1, 1, 1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTroVe, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnThemMonHocMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(77, 77, 77))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTroVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTroVeActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
        new GiaoDienChinh();
    }//GEN-LAST:event_btnTroVeActionPerformed

    private void btnThemMonHocMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemMonHocMoiActionPerformed
        // Xóa các text để thêm môn  mới
        txtTenMonHoc.setEnabled(true);
        txtMaHocPhan.setEnabled(true);
        txtGioiThieu.setEnabled(true);
        spSoChuong.setEnabled(true);
        btnLuu.setEnabled(true);
        txtGioiThieu.setText("");
        txtMaHocPhan.setText("");
        txtTenMonHoc.setText("");
        spSoChuong.setValue(1);

    }//GEN-LAST:event_btnThemMonHocMoiActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // Lưu Môn Học và show lên list
        if (txtTenMonHoc.getText().isEmpty() || txtMaHocPhan.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nhập tên môn học và mã học phần!");
        } 
        else if (!kiemTraTenvaMaHocPhan()) {
            for (MonHoc monHoc : listMonHoc) {
                if (monHoc.getTenMonHoc().equals(txtTenMonHoc.getText().trim()) && monHoc.getMaHocPhan().equals(txtMaHocPhan.getText().trim())) {
                    monHoc.setGioiThieu(txtGioiThieu.getText());
                    monHoc.setSoChuong((int) spSoChuong.getValue());
                }
            } 
        } 
        else {
            MonHoc monHoc = new MonHoc();
            monHoc.setTenMonHoc(txtTenMonHoc.getText());
            monHoc.setSoChuong((int) spSoChuong.getValue());
            monHoc.setGioiThieu(txtGioiThieu.getText());
            monHoc.setMaHocPhan(txtMaHocPhan.getText());
            monHoc.setDsCauHoiTL(new ArrayList<>());
            monHoc.setDsCauHoiTN(new ArrayList<>());
            monHoc.setDsDeThi(new ArrayList<>());
            modelListMonHoc.addElement(monHoc);
            jListDanhSachMonHoc.setModel(modelListMonHoc);
            listMonHoc.add(monHoc);
            
        }
        writeListMonHoc();
        txtTenMonHoc.setEnabled(false);
        txtMaHocPhan.setEnabled(false);
        txtGioiThieu.setEnabled(false);
        spSoChuong.setEnabled(false);
        btnLuu.setEnabled(false);
        btnCapNhat.setEnabled(false);
        btnXoa.setEnabled(false);
        JOptionPane.showMessageDialog(null, "Đã lưu Thành Công!");
    }//GEN-LAST:event_btnLuuActionPerformed

    private void jListDanhSachMonHocValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListDanhSachMonHocValueChanged
        // Lựa chọn 1 đối tượng trong list 
//        selectedMonHoc = jListDanhSachMonHoc.getSelectedValue();
//        selectecMonHocindex = jListDanhSachMonHoc.getSelectedIndex();
//        // System.out.println(selectedMonHoc);
//        for (MonHoc monHoc : listMonHoc) {
//            if (monHoc.getTenMonHoc().equals(selectedMonHoc)) {
//                txtGioiThieu.setText(monHoc.getGioiThieu());
//                txtMaHocPhan.setText(monHoc.getMaHocPhan());
//                txtTenMonHoc.setText(monHoc.getTenMonHoc());
//                spSoChuong.setValue(monHoc.getSoChuong());
//                break;
//            }
//        }

    }//GEN-LAST:event_jListDanhSachMonHocValueChanged

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
       spSoChuong.setEnabled(true);
       txtGioiThieu.setEnabled(true);
       btnLuu.setEnabled(true);
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        //Xóa Môn Học : 
        for (int i = 0; i < listMonHoc.size(); i++) {
            if (listMonHoc.get(i).getTenMonHoc().equals(selectedMonHoc.getTenMonHoc())) {
                txtGioiThieu.setText("");
                txtMaHocPhan.setText("");
                txtTenMonHoc.setText("");
                spSoChuong.setValue(1);
                modelListMonHoc.removeElement(selectedMonHoc);
                jListDanhSachMonHoc.setModel(modelListMonHoc);
                listMonHoc.remove(listMonHoc.get(i));
                writeListMonHoc();
                JOptionPane.showMessageDialog(null, "Đã Xóa Thành Công!");
                break;
            }
        }
        btnCapNhat.setEnabled(false);
        btnXoa.setEnabled(false);
    }//GEN-LAST:event_btnXoaActionPerformed

    private void jListDanhSachMonHocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListDanhSachMonHocMouseClicked
        // TODO add your handling code here:
        selectedMonHoc = jListDanhSachMonHoc.getSelectedValue();
        txtGioiThieu.setText(selectedMonHoc.getGioiThieu());
        txtMaHocPhan.setText(selectedMonHoc.getMaHocPhan());
        txtTenMonHoc.setText(selectedMonHoc.getTenMonHoc());
        spSoChuong.setValue(selectedMonHoc.getSoChuong());
        
        btnCapNhat.setEnabled(true);
        btnXoa.setEnabled(true);
        txtTenMonHoc.setEnabled(false);
        txtMaHocPhan.setEnabled(false);
        txtGioiThieu.setEnabled(false);
        spSoChuong.setEnabled(false);
        btnLuu.setEnabled(false);
    }//GEN-LAST:event_jListDanhSachMonHocMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyMonHoc.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyMonHoc.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyMonHoc.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyMonHoc.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyMonHoc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnThemMonHocMoi;
    private javax.swing.JButton btnTroVe;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<MonHoc> jListDanhSachMonHoc;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner spSoChuong;
    private javax.swing.JTextArea txtGioiThieu;
    private javax.swing.JTextField txtMaHocPhan;
    private javax.swing.JTextField txtTenMonHoc;
    // End of variables declaration//GEN-END:variables

    private void readListMonHoc() {
        try {
            FileInputStream fileReader = new FileInputStream("DanhSachMonHoc.dat");
            ObjectInputStream inputStream = new ObjectInputStream(fileReader);
            listMonHoc = (ArrayList<MonHoc>) inputStream.readObject();
            inputStream.close();
            fileReader.close();

        } catch (FileNotFoundException ex) {
            Logger.getLogger(QuanLyMonHoc.class
                    .getName()).log(Level.SEVERE, null, ex);

        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(QuanLyMonHoc.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }
   
   private void writeListMonHoc() {
        try {
            FileOutputStream fileOutputStream = new FileOutputStream("DanhSachMonHoc.dat",false);
            ObjectOutputStream outputStream = new ObjectOutputStream(fileOutputStream);
            outputStream.writeObject(listMonHoc);
            outputStream.close();
            fileOutputStream.close();
        } catch (IOException e) {
            System.out.println(e.toString());
        }
    }

    public boolean kiemTraTenvaMaHocPhan() {
        for (MonHoc monHoc : listMonHoc) {
            if (monHoc.getTenMonHoc().equals(txtTenMonHoc.getText().trim()) || monHoc.getMaHocPhan().equals(txtMaHocPhan.getText().trim())) {
                return false;
            }
        }
        return true;
    }

}
