/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Dimension;
import java.awt.Graphics;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.Collections;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import models.CauHoi;
import models.CauHoiTracNghiem;
import models.CauHoiTuLuan;
import models.DapAn;
import models.DeThi;
import models.MonHoc;

/**
 *
 * @author DANG TRUNG ANH
 */
public class TaoDeThiBangTay extends javax.swing.JFrame {

    private DefaultListModel<CauHoi>modelCauTrongDe=new DefaultListModel<>();
    
    private ArrayList<CauHoiTracNghiem>dsCauTNTrongDe=new ArrayList<>();
    private ArrayList<CauHoiTuLuan>dsCauTLTrongDe=new ArrayList<>();
    
    private ArrayList<CauHoiTuLuan>dsCauHoiTL=new ArrayList<>();
    private ArrayList<CauHoiTracNghiem>dsCauHoiTN=new ArrayList<>();
    
    private ArrayList<DeThi>dsDe=new ArrayList<>();
    
    private ArrayList<CauHoi>dsCauHoiLoai;
    private ArrayList<CauHoi>dsCauHoiChuong;
    
    MonHoc monHocSelected;
    private ArrayList<MonHoc> listMonHoc = new ArrayList<>();
    
    DeThi deThiSelected;
    
    /**
     * Creates new form ChonCauHoi
     */
    public TaoDeThiBangTay(MonHoc monHocSelected, DeThi deThiSelected) {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setTitle("Tạo đề thi bằng tay");
        this.monHocSelected = monHocSelected;
        this.deThiSelected = deThiSelected;
        readDanhSachMonHoc();
        dsCauHoiTL = monHocSelected.getDsCauHoiTL();
        dsCauHoiTN = monHocSelected.getDsCauHoiTN();
        dsDe = monHocSelected.getDsDeThi();
        hienThi();
    }
    
    public TaoDeThiBangTay() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel(){
            ImageIcon icon = new ImageIcon("src\\anh\\taodethibangtay.jpg");
            public void paintComponent(Graphics g){
                Dimension d = getSize();
                g.drawImage(icon.getImage(), 0, 0, d.width, d.height, null);
                setOpaque(false);
                super.paintComponent(g);
            }
        };
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        listCauHoi = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaMoTa = new javax.swing.JTextArea();
        btnThemCauHoi = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtTenDeThi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txaDeThi = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        listCauTrongDe = new javax.swing.JList<>();
        btnXoaCauHoi = new javax.swing.JButton();
        btnXuatFile = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtThoiGian = new javax.swing.JTextField();
        txtNamhoc = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        raKy1 = new javax.swing.JRadioButton();
        raKy2 = new javax.swing.JRadioButton();
        raKyHe = new javax.swing.JRadioButton();
        btnLuuDeThi = new javax.swing.JButton();
        btnTroLai = new javax.swing.JButton();
        cbLoaiCau = new javax.swing.JComboBox<>();
        cbChuong = new javax.swing.JComboBox<>();
        cbDoKho = new javax.swing.JComboBox<>();
        btnXaoTronCauHoi = new javax.swing.JButton();
        btnXoaTatCa = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        btnXaoTronDapAn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Danh sách câu hỏi");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Tìm kiếm");

        listCauHoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listCauHoiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listCauHoi);

        txaMoTa.setColumns(20);
        txaMoTa.setRows(5);
        jScrollPane2.setViewportView(txaMoTa);

        btnThemCauHoi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThemCauHoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anh/themda.png"))); // NOI18N
        btnThemCauHoi.setText("Thêm vào đề thi");
        btnThemCauHoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemCauHoiActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Tên đề thi :");

        txtTenDeThi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTenDeThiKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText("Danh sách các câu trong đề");

        txaDeThi.setColumns(20);
        txaDeThi.setRows(5);
        jScrollPane3.setViewportView(txaDeThi);

        jScrollPane4.setViewportView(listCauTrongDe);

        btnXoaCauHoi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnXoaCauHoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anh/xoada.png"))); // NOI18N
        btnXoaCauHoi.setText("Xóa câu hỏi");
        btnXoaCauHoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaCauHoiActionPerformed(evt);
            }
        });

        btnXuatFile.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnXuatFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anh/xuatfile.png"))); // NOI18N
        btnXuatFile.setText("Xuất ra file");
        btnXuatFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatFileActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 204));
        jLabel6.setText("Thông tin về đề thi");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Thời gian :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Năm học :");

        txtThoiGian.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        txtThoiGian.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtThoiGian.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtThoiGianKeyReleased(evt);
            }
        });

        txtNamhoc.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        txtNamhoc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNamhoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamhocActionPerformed(evt);
            }
        });
        txtNamhoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNamhocKeyReleased(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Kỳ :");

        buttonGroup1.add(raKy1);
        raKy1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        raKy1.setText("1");
        raKy1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                raKy1ItemStateChanged(evt);
            }
        });

        buttonGroup1.add(raKy2);
        raKy2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        raKy2.setText("2");
        raKy2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                raKy2ItemStateChanged(evt);
            }
        });

        buttonGroup1.add(raKyHe);
        raKyHe.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        raKyHe.setText("Hè");
        raKyHe.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                raKyHeItemStateChanged(evt);
            }
        });

        btnLuuDeThi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLuuDeThi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anh/luu.png"))); // NOI18N
        btnLuuDeThi.setText("Lưu đề thi");
        btnLuuDeThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuDeThiActionPerformed(evt);
            }
        });

        btnTroLai.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnTroLai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anh/back.png"))); // NOI18N
        btnTroLai.setText("Trở về");
        btnTroLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTroLaiActionPerformed(evt);
            }
        });

        cbLoaiCau.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbLoaiCau.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LOẠI CÂU", "TẤT CẢ", "TRẮC NGHIỆM", "TỰ LUẬN" }));
        cbLoaiCau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLoaiCauActionPerformed(evt);
            }
        });

        cbChuong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbChuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbChuongActionPerformed(evt);
            }
        });

        cbDoKho.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbDoKho.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ĐỘ KHÓ", "DỄ", "TRUNG BÌNH", "KHÓ" }));
        cbDoKho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDoKhoActionPerformed(evt);
            }
        });

        btnXaoTronCauHoi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnXaoTronCauHoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anh/xaotron.png"))); // NOI18N
        btnXaoTronCauHoi.setText("Xáo trộn câu hỏi");
        btnXaoTronCauHoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXaoTronCauHoiActionPerformed(evt);
            }
        });

        btnXoaTatCa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnXoaTatCa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anh/deleteall.png"))); // NOI18N
        btnXoaTatCa.setText("Xóa tất cả");
        btnXoaTatCa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaTatCaActionPerformed(evt);
            }
        });

        btnTimKiem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anh/search.png"))); // NOI18N
        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 204));
        jLabel11.setText("Thông tin câu hỏi:");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnXaoTronDapAn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnXaoTronDapAn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anh/xaotroncauhoi.png"))); // NOI18N
        btnXaoTronDapAn.setText("Xáo trộn đáp án");
        btnXaoTronDapAn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXaoTronDapAnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnTroLai, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnXoaCauHoi, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnXoaTatCa, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnXaoTronCauHoi, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnXuatFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btnLuuDeThi, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTenDeThi))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNamhoc, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(txtThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(raKy1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(raKy2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(raKyHe)
                                .addGap(9, 9, 9))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTimKiem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnTimKiem))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cbLoaiCau, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbChuong, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(cbDoKho, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnXaoTronDapAn)
                                .addGap(18, 18, 18)
                                .addComponent(btnThemCauHoi))
                            .addComponent(jScrollPane2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnThemCauHoi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnXaoTronDapAn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbDoKho, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cbLoaiCau, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cbChuong, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(raKy1)
                                    .addComponent(raKy2)
                                    .addComponent(raKyHe)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNamhoc, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTenDeThi, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnXoaCauHoi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnXoaTatCa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnXuatFile, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                                .addComponent(btnXaoTronCauHoi, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnLuuDeThi, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnTroLai, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator3))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnLuuDeThi, btnXaoTronCauHoi, btnXuatFile});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void btnThemCauHoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemCauHoiActionPerformed
        // TODO add your handling code here:
        CauHoi selectCauHoi=listCauHoi.getSelectedValue();
        
        if(selectCauHoi == null) {
            JOptionPane.showMessageDialog(null, "CHƯA CHỌN CÂU HỎI");
        }
        else {
            //thêm vào danh sách
            if(selectCauHoi instanceof CauHoiTracNghiem) {
                int count = 0;
                //kiểm tra xem câu hỏi đã tồn tại trong danh sách hay chưa
                for(CauHoiTracNghiem tracNghiem : dsCauTNTrongDe) {
                    if(selectCauHoi.getDeBai().equals(tracNghiem.getDeBai())) {
                        count ++;
                        JOptionPane.showMessageDialog(null, "CÂU HỎI ĐÃ CÓ TRONG ĐỀ");
                        break;
                    }
                }
                if(count == 0) {
                    dsCauTNTrongDe.add((CauHoiTracNghiem) selectCauHoi);
                    JOptionPane.showMessageDialog(null, "THÊM THÀNH CÔNG");
                }
            }
            else {
                int count = 0;
                //kiểm tra xem câu hỏi đã tồn tại trong danh sách hay chưa
                for(CauHoiTuLuan tuLuan : dsCauTLTrongDe) {
                    if(selectCauHoi.getDeBai().equals(tuLuan.getDeBai())) {
                        count ++;
                        JOptionPane.showMessageDialog(null, "CÂU HỎI ĐÃ CÓ TRONG ĐỀ");
                        break;
                    }
                }
                if(count == 0) {
                    dsCauTLTrongDe.add((CauHoiTuLuan) selectCauHoi);
                    JOptionPane.showMessageDialog(null, "THÊM THÀNH CÔNG");
                }
            }
            
            modelCauTrongDe = new DefaultListModel<>();
            for(CauHoiTracNghiem tracNghiem : dsCauTNTrongDe) {
                modelCauTrongDe.addElement(tracNghiem);
            }
            for(CauHoiTuLuan tuLuan : dsCauTLTrongDe) {
                modelCauTrongDe.addElement(tuLuan);
            }
            listCauTrongDe.setModel(modelCauTrongDe);
            
            hienThiNoiDungDe();
        }
    }//GEN-LAST:event_btnThemCauHoiActionPerformed

    private void btnTroLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTroLaiActionPerformed
        // TODO add your handling code here:
        XayDungDeThi xddt=new XayDungDeThi(monHocSelected);
        xddt.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnTroLaiActionPerformed

    private void listCauHoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listCauHoiMouseClicked
        // TODO add your handling code here:
        CauHoi selectCauHoi=listCauHoi.getSelectedValue();
        txaMoTa.setText(selectCauHoi.inThongTinCauHoi());
        if(selectCauHoi instanceof CauHoiTracNghiem) {
            if(((CauHoiTracNghiem) selectCauHoi).isCoTheXaoTronDuoc()) {
                btnXaoTronDapAn.setEnabled(true);
            }
            else {
                btnXaoTronDapAn.setEnabled(false);
            }
        }
        else {
            btnXaoTronDapAn.setEnabled(false);
        }
    }//GEN-LAST:event_listCauHoiMouseClicked

    private void btnXoaCauHoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaCauHoiActionPerformed
        // TODO add your handling code here:
        CauHoi selectCauHoi=listCauTrongDe.getSelectedValue();
        
        if(selectCauHoi == null) {
            JOptionPane.showMessageDialog(null, "CHỌN CÂU HỎI MUỐN XÓA");
        }
        else {
            //xóa trong danh sách
            if(selectCauHoi instanceof CauHoiTracNghiem) {
                dsCauTNTrongDe.remove(selectCauHoi);
            }
            else {
                dsCauTLTrongDe.remove(selectCauHoi);
            }

            //xóa trong modellist
            modelCauTrongDe.removeElement(selectCauHoi);

            listCauTrongDe.setModel(modelCauTrongDe);
            hienThiNoiDungDe();
            JOptionPane.showMessageDialog(null, "XÓA THÀNH CÔNG");
        }
        
    }//GEN-LAST:event_btnXoaCauHoiActionPerformed

    private void btnLuuDeThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuDeThiActionPerformed
        // TODO add your handling code here:
        
        //xóa đề thi đang sửa
        if(deThiSelected != null) {
            for(DeThi deThi:dsDe) {
                if(deThi.getTenDe().equals(deThiSelected.getTenDe())) {
                    dsDe.remove(deThi);
                    break;
                }
            }
        }
        
        //kiểm tra xem đã có đề thi chưa
        int count = 0;
        for(DeThi deThi : dsDe) {
            if(deThi.getTenDe().equals(txtTenDeThi.getText())) {
                count++;
                JOptionPane.showMessageDialog(null, "ĐỀ THI ĐÃ TỒN TẠI");
                break;
            }
        }
        
        if(count == 0) {
            //thêm đề thi mới
            try {
                DeThi deThi=new DeThi();
                deThi.setDsCauHoiTN(dsCauTNTrongDe);
                deThi.setDsCauHoiTL(dsCauTLTrongDe);
                deThi.setTenDe(txtTenDeThi.getText());
                deThi.setNamHoc(txtNamhoc.getText());
                deThi.setThoiGian(Integer.parseInt(txtThoiGian.getText()));
                String ky;
                if(raKy1.isSelected()) {
                    ky="1";
                }
                else if(raKy2.isSelected()) {
                    ky="2";
                }
                else {
                    ky="hè";
                }
                deThi.setKyHoc(ky);
                dsDe.add(deThi);
                for(MonHoc monHoc : listMonHoc) {
                    if(monHoc.getTenMonHoc().equals(monHocSelected.getTenMonHoc())) {
                        monHoc.setDsDeThi(dsDe);
                    }
                }
                JOptionPane.showMessageDialog(null, "LƯU THÀNH CÔNG");
            }
            catch(Exception ex) {
                JOptionPane.showMessageDialog(null, "Chưa điền đủ thông tin năm học, thời gian, kỳ, mời nhập lại!");

            }
            
            //lưu danh sách đề thi
            writeDanhSachMonHoc();
        }
    }//GEN-LAST:event_btnLuuDeThiActionPerformed

    private void btnXuatFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatFileActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser=new JFileChooser();
        if(chooser.showSaveDialog(null)==JFileChooser.APPROVE_OPTION) {
            FileWriter fw=null;
            try {
                File file=chooser.getSelectedFile();
                fw = new FileWriter(file+".doc"); // tạo ra 1 file mới với giá trị truyền vào là tên file
                fw.write(txaDeThi.getText()); // ghi string vào file
                fw.close();
                JOptionPane.showMessageDialog(null, "THÀNH CÔNG");
            } catch (IOException ex) {
                Logger.getLogger(TaoDeThiBangTay.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                try {
                    fw.close();
                } catch (IOException ex) {
                    Logger.getLogger(TaoDeThiBangTay.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
        }
    }//GEN-LAST:event_btnXuatFileActionPerformed

    private void cbLoaiCauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLoaiCauActionPerformed
        // TODO add your handling code here:
        String loaiCau=(String) cbLoaiCau.getSelectedItem();
        DefaultListModel modelListCauHoi=new DefaultListModel();
        dsCauHoiLoai=new ArrayList<>();
        if(loaiCau.equals("LOẠI CÂU")) {
            cbChuong.setEnabled(false);
            cbDoKho.setEnabled(false);
            return;
        }
        if(loaiCau.equals("TẤT CẢ")) {
            for(CauHoiTuLuan cauHoiTL:dsCauHoiTL) {
                dsCauHoiLoai.add(cauHoiTL);
                modelListCauHoi.addElement(cauHoiTL);
            }
            for(CauHoiTracNghiem cauHoiTN:dsCauHoiTN) {
                dsCauHoiLoai.add(cauHoiTN);
                modelListCauHoi.addElement(cauHoiTN);
            }
        }
        if(loaiCau.equals("TRẮC NGHIỆM")) {
            for(CauHoiTracNghiem cauHoiTN:dsCauHoiTN) {
                dsCauHoiLoai.add(cauHoiTN);
                modelListCauHoi.addElement(cauHoiTN);
            }
        }
        if(loaiCau.equals("TỰ LUẬN")) {
            for(CauHoiTuLuan cauHoiTL:dsCauHoiTL) {
                dsCauHoiLoai.add(cauHoiTL);
                modelListCauHoi.addElement(cauHoiTL);
            }
        }
        listCauHoi.setModel(modelListCauHoi);
        cbChuong.setEnabled(true);
        cbDoKho.setEnabled(false);
    }//GEN-LAST:event_cbLoaiCauActionPerformed

    private void cbChuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbChuongActionPerformed
        // TODO add your handling code here:
        String chuong=(String) cbChuong.getSelectedItem();
        DefaultListModel modelListCauHoi=new DefaultListModel();
        dsCauHoiChuong=new ArrayList<>();
        if(chuong.equals("CHƯƠNG")) {
            cbDoKho.setEnabled(false);
            return;
        }
        for(CauHoi cauHoi:dsCauHoiLoai) {
            if(cauHoi.getChuong().equals(chuong)) {
                dsCauHoiChuong.add(cauHoi);
                modelListCauHoi.addElement(cauHoi);
            }
        }
        listCauHoi.setModel(modelListCauHoi);
        cbDoKho.setEnabled(true);
    }//GEN-LAST:event_cbChuongActionPerformed

    private void cbDoKhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDoKhoActionPerformed
        // TODO add your handling code here:
        String doKho=(String) cbDoKho.getSelectedItem();
        DefaultListModel modelListCauHoi=new DefaultListModel();
        if(doKho.equals("ĐỘ KHÓ")) {
            return;
        }
        if(doKho.equals("DỄ")) {
            for(CauHoi cauHoi:dsCauHoiChuong) {
                if(cauHoi.getDoKho().equals("Dễ")) {
                    modelListCauHoi.addElement(cauHoi);
                }
            }
        }
        if(doKho.equals("TRUNG BÌNH")) {
            for(CauHoi cauHoi:dsCauHoiChuong) {
                if(cauHoi.getDoKho().equals("Trung Bình")) {
                    modelListCauHoi.addElement(cauHoi);
                }
            }
        }
        if(doKho.equals("KHÓ")) {
            for(CauHoi cauHoi:dsCauHoiChuong) {
                if(cauHoi.getDoKho().equals("Khó")) {
                    modelListCauHoi.addElement(cauHoi);
                }
            }
        }
        listCauHoi.setModel(modelListCauHoi);
    }//GEN-LAST:event_cbDoKhoActionPerformed

    private void btnXaoTronCauHoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXaoTronCauHoiActionPerformed
        // TODO add your handling code here:
        if(dsCauTLTrongDe.isEmpty() && dsCauTNTrongDe.isEmpty()) {
            JOptionPane.showMessageDialog(null, "KHÔNG CÓ CÂU HỎI");
        }
        else {
            Collections.shuffle(dsCauTNTrongDe);
            Collections.shuffle(dsCauTLTrongDe);
            
            modelCauTrongDe = new DefaultListModel<>();
            for(CauHoiTracNghiem tracNghiem : dsCauTNTrongDe) {
                modelCauTrongDe.addElement(tracNghiem);
            }
            for(CauHoiTuLuan tuLuan : dsCauTLTrongDe) {
                modelCauTrongDe.addElement(tuLuan);
            }
            listCauTrongDe.setModel(modelCauTrongDe);
            
            hienThiNoiDungDe();
            JOptionPane.showMessageDialog(null, "ĐÃ TRỘN CÂU HỎI");
        }
    }//GEN-LAST:event_btnXaoTronCauHoiActionPerformed

    private void btnXoaTatCaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaTatCaActionPerformed
        // TODO add your handling code here:
        //xóa tất cả câu hỏi trong danh sách
        int result = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa tất cả", 
                "Thông báo", JOptionPane.YES_NO_OPTION);
        if(result == JOptionPane.YES_OPTION) {
            dsCauTNTrongDe.removeAll(dsCauTNTrongDe);
            dsCauTLTrongDe.removeAll(dsCauTLTrongDe);

            //xóa tất cả câu hỏi trong model
            modelCauTrongDe.removeAllElements();

            listCauTrongDe.setModel(modelCauTrongDe);
            hienThiNoiDungDe();
            JOptionPane.showMessageDialog(null, "ĐÃ XÓA HẾT");
        }
    }//GEN-LAST:event_btnXoaTatCaActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        if(txtTimKiem.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "CHƯA NHẬP THÔNG TIN TÌM KIẾM");
        }
        else {
            DefaultListModel modelCauHoi=new DefaultListModel();
            for(CauHoiTracNghiem chtn:dsCauHoiTN) {
                if(chtn.getDeBai().contains(txtTimKiem.getText())) {
                    modelCauHoi.addElement(chtn);
                }
            }
            for(CauHoiTuLuan chtl:dsCauHoiTL) {
                if(chtl.getDeBai().contains(txtTimKiem.getText())) {
                    modelCauHoi.addElement(chtl);
                }
            }
            listCauHoi.setModel(modelCauHoi);
        }
        
        cbLoaiCau.setSelectedIndex(0);
        cbChuong.setSelectedIndex(0);
        cbDoKho.setSelectedIndex(0);
        
        cbChuong.setEnabled(false);
        cbDoKho.setEnabled(false);
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void raKy1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_raKy1ItemStateChanged
        // TODO add your handling code here:
        hienThiNoiDungDe();
    }//GEN-LAST:event_raKy1ItemStateChanged

    private void raKy2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_raKy2ItemStateChanged
        // TODO add your handling code here:
        hienThiNoiDungDe();
    }//GEN-LAST:event_raKy2ItemStateChanged

    private void raKyHeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_raKyHeItemStateChanged
        // TODO add your handling code here:
        hienThiNoiDungDe();
    }//GEN-LAST:event_raKyHeItemStateChanged

    private void txtThoiGianKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtThoiGianKeyReleased
        // TODO add your handling code here:
        hienThiNoiDungDe();
    }//GEN-LAST:event_txtThoiGianKeyReleased

    private void txtNamhocKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamhocKeyReleased
        // TODO add your handling code here:
        hienThiNoiDungDe();
    }//GEN-LAST:event_txtNamhocKeyReleased

    private void txtTenDeThiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTenDeThiKeyReleased
        // TODO add your handling code here:
        hienThiNoiDungDe();
    }//GEN-LAST:event_txtTenDeThiKeyReleased

    private void txtNamhocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamhocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamhocActionPerformed

    private void btnXaoTronDapAnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXaoTronDapAnActionPerformed
        // TODO add your handling code here:
        CauHoi selectCauHoi=listCauHoi.getSelectedValue();
        ArrayList<DapAn> dsDapAn = new ArrayList<>();
        if(selectCauHoi instanceof CauHoiTracNghiem) {
            dsDapAn = ((CauHoiTracNghiem) selectCauHoi).getDapAn();
            Collections.shuffle(dsDapAn);
            ((CauHoiTracNghiem) selectCauHoi).setDapAn(dsDapAn);
        }
        txaMoTa.setText(selectCauHoi.inThongTinCauHoi());
        JOptionPane.showMessageDialog(null, "Đã xáo trộn đáp án");
    }//GEN-LAST:event_btnXaoTronDapAnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaoDeThiBangTay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaoDeThiBangTay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaoDeThiBangTay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaoDeThiBangTay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TaoDeThiBangTay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLuuDeThi;
    private javax.swing.JButton btnThemCauHoi;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnTroLai;
    private javax.swing.JButton btnXaoTronCauHoi;
    private javax.swing.JButton btnXaoTronDapAn;
    private javax.swing.JButton btnXoaCauHoi;
    private javax.swing.JButton btnXoaTatCa;
    private javax.swing.JButton btnXuatFile;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cbChuong;
    private javax.swing.JComboBox<String> cbDoKho;
    private javax.swing.JComboBox<String> cbLoaiCau;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JList<CauHoi> listCauHoi;
    private javax.swing.JList<CauHoi> listCauTrongDe;
    private javax.swing.JRadioButton raKy1;
    private javax.swing.JRadioButton raKy2;
    private javax.swing.JRadioButton raKyHe;
    private javax.swing.JTextArea txaDeThi;
    private javax.swing.JTextArea txaMoTa;
    private javax.swing.JTextField txtNamhoc;
    private javax.swing.JTextField txtTenDeThi;
    private javax.swing.JTextField txtThoiGian;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables

    
    public void hienThi() {
        DefaultListModel<CauHoi> modelList=new DefaultListModel<>();
        for(CauHoiTuLuan tuLuan:dsCauHoiTL) {
            modelList.addElement(tuLuan);
        }
        for(CauHoiTracNghiem tracNghiem:dsCauHoiTN) {
            modelList.addElement(tracNghiem);
        }
        listCauHoi.setModel(modelList);
            
        //hiển thị chương trên combobox
        cbChuong.addItem("CHƯƠNG");
        for(int i=1;i<=monHocSelected.getSoChuong();++i) {
            cbChuong.addItem("Chương "+i);
        }
        cbChuong.setEnabled(false);
        cbDoKho.setEnabled(false);
        
        //hiển thị thông tin đề được sửa
        if(deThiSelected != null) {
            //hiển thị các câu có trong đề
            for(CauHoiTracNghiem chtn : deThiSelected.getDsCauHoiTN()){
                dsCauTNTrongDe.add(chtn);
                modelCauTrongDe.addElement(chtn);
            }
            for(CauHoiTuLuan chtl : deThiSelected.getDsCauHoiTL()){
                dsCauTLTrongDe.add(chtl);
                modelCauTrongDe.addElement(chtl);
            }
            listCauTrongDe.setModel(modelCauTrongDe);
            
            //lấy các giá trị trong đề
            txtNamhoc.setText(deThiSelected.getNamHoc());
            txtTenDeThi.setText(deThiSelected.getTenDe());
            txtThoiGian.setText(String.valueOf(deThiSelected.getThoiGian()));
            if(deThiSelected.getKyHoc().equals("1")) {
                raKy1.setSelected(true);
            }
            if(deThiSelected.getKyHoc().equals("2")) {
                raKy2.setSelected(true);
            }
            if(deThiSelected.getKyHoc().equals("hè")) {
                raKyHe.setSelected(true);
            }
        }
        
        hienThiNoiDungDe();
    }
     
    private void hienThiNoiDungDe() {
        String tracNghiem="";
        String tuLuan="";
        String tieuDe="";
        String ky="";
        int i=1;
        
        if(raKy1.isSelected()) {
            ky="1";
        }
        else if(raKy2.isSelected()) {
            ky="2";
        }
        else if(raKyHe.isSelected()) {
            ky="hè";
        }
        
        tieuDe+="Đề thi : "+txtTenDeThi.getText()+"          "+"Mã học phần : "+monHocSelected.getMaHocPhan()+"          "+
                "Học phần : "+monHocSelected.getTenMonHoc()+"\n"+"Năm học : "+txtNamhoc.getText()+"          "+"Học kỳ : "+ky+
                "          "+"Thời gian : "+txtThoiGian.getText()+" phút"+"\n";
        
        for(CauHoiTracNghiem ch:dsCauTNTrongDe) {
            tracNghiem+="Câu "+i+" : "+ch.inCauHoi();
            i++;
        }
        for(CauHoiTuLuan ch:dsCauTLTrongDe) {
            tuLuan+="Câu "+i+" : "+ch.inCauHoi();
            i++;
        }
        String deThi=tieuDe+tracNghiem+tuLuan;
        txaDeThi.setText(deThi);
    }
    
    private void readDanhSachMonHoc() {
        try {
            FileInputStream fileReader = new FileInputStream("DanhSachMonHoc.dat");
            ObjectInputStream inputStream = new ObjectInputStream(fileReader);
            listMonHoc = (ArrayList<MonHoc>) inputStream.readObject();
            inputStream.close();
            fileReader.close();

        } catch (FileNotFoundException ex) {
            Logger.getLogger(QuanLyMonHoc.class
                    .getName()).log(Level.SEVERE, null, ex);

        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(QuanLyMonHoc.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void writeDanhSachMonHoc() {
        try {
            FileOutputStream fileOutputStream = new FileOutputStream("DanhSachMonHoc.dat",false);
            ObjectOutputStream outputStream = new ObjectOutputStream(fileOutputStream);
            outputStream.writeObject(listMonHoc);
            outputStream.close();
            fileOutputStream.close();
        } catch (IOException e) {
            System.out.println(e.toString());
        }
    }
        
}
