/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import models.DapAn;

/**
 *
 * @author DANG TRUNG ANH
 */
public class ThemDapAn extends javax.swing.JFrame {

    /**
     * Creates new form ThemDapAn
     */
    
    private DefaultListModel modelDapAn; //Đáp án của câu hỏi hiện tại đang được chọn
    private javax.swing.JList<DapAn> danhSachDapAn;
    
    //-----Thuộc tính đánh dấu chức năng cần làm
    private int chonChucNang;
    //Với chonChucNang = -1, thêm đáp án mới cho câu hỏi hiện tại
    //Với chonChucNang >= 0, chỉ vị trí, chỉnh sửa cho đáp án hiện tại, của câu hỏi hiện tại
    
    private ArrayList<DapAn> dsDapAn = new ArrayList<>();
    
    public ThemDapAn(int chonChucNang, ArrayList<DapAn> dsDapAn, javax.swing.JList<DapAn> danhSachDapAn, DefaultListModel modelDapAn) {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setTitle("Thêm đáp án");
        this.setResizable(false);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        //--------------------
        this.modelDapAn = modelDapAn;
        this.danhSachDapAn = danhSachDapAn;
        this.chonChucNang = chonChucNang;
        this.dsDapAn = dsDapAn;
//        dapAn = new DapAn();
        //===================================================
        if (chonChucNang >= 0) {
            //Chỉnh sửa đáp án cho câu hỏi hiện tại, chonChucNang chỉ index của đáp án đó
            this.setTitle("Cập nhật đáp án");
            noiDungDapAn.setText((String) dsDapAn.get(chonChucNang).getNoiDung());
            dapAnDungCheckBox.setSelected(dsDapAn.get(chonChucNang).isDapAnDung());
        }
        else {
            this.setTitle("Thêm đáp án");
        }
        
    }
    
    public ThemDapAn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel(){
            ImageIcon icon = new ImageIcon("src\\anh\\themdapan.jpg");
            public void paintComponent(Graphics g){
                Dimension d = getSize();
                g.drawImage(icon.getImage(), 0, 0, d.width, d.height, null);
                setOpaque(false);
                super.paintComponent(g);
            }
        };
        jLabel1 = new javax.swing.JLabel();
        noiDungDapAn = new javax.swing.JTextField();
        dapAnDungCheckBox = new javax.swing.JCheckBox();
        OKbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Đáp án");

        dapAnDungCheckBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dapAnDungCheckBox.setText("Đáp án đúng");
        dapAnDungCheckBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                dapAnDungCheckBoxStateChanged(evt);
            }
        });

        OKbutton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        OKbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anh/select.png"))); // NOI18N
        OKbutton.setText("OK");
        OKbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(noiDungDapAn, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(OKbutton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dapAnDungCheckBox, javax.swing.GroupLayout.Alignment.TRAILING)))))
                .addGap(62, 62, 62))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(noiDungDapAn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dapAnDungCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(OKbutton)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OKbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKbuttonActionPerformed
        // TODO add your handling code here:
        if(noiDungDapAn.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Không được để trống nội dung đáp án!");
            return;
        }
        
        if(chonChucNang < 0) {
            DapAn dapAn = new DapAn();
            dapAn.setNoiDung(noiDungDapAn.getText());
            if(dapAnDungCheckBox.isSelected()) {
                dapAn.setDapAnDung(true);
            }
            else {
                dapAn.setDapAnDung(false);
            }
            dsDapAn.add(dapAn);
            hienThiDapAn();
        } 
        else {
            DapAn dapAn = new DapAn();
            dapAn.setNoiDung(noiDungDapAn.getText());
            if(dapAnDungCheckBox.isSelected()) {
                dapAn.setDapAnDung(true);
            }
            else {
                dapAn.setDapAnDung(false);
            }
            dsDapAn.remove(chonChucNang);
            dsDapAn.add(chonChucNang, dapAn);
            hienThiDapAn();
        }
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_OKbuttonActionPerformed

    private void dapAnDungCheckBoxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_dapAnDungCheckBoxStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_dapAnDungCheckBoxStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemDapAn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemDapAn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemDapAn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemDapAn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThemDapAn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OKbutton;
    private javax.swing.JCheckBox dapAnDungCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField noiDungDapAn;
    // End of variables declaration//GEN-END:variables

    private void hienThiDapAn() {
        modelDapAn = new DefaultListModel();
        for(DapAn da : dsDapAn) {
            modelDapAn.addElement(da);
            if(da.isDapAnDung() == true) {
            }
        }
        danhSachDapAn.setModel(modelDapAn);
    }

}
